site_name: pyGenClean - Automated Data Clean Up

# GitHub information
repo_url: https://github.com/lemieuxl/pyGenClean
repo_name: lemieuxl/pyGenClean

# Code highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html

# Watch changes in the source directory
watch:
  - pygenclean

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true
            members_order: source
          paths: [pygenclean]
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv

# Theme
theme:
  name: material

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - search.highlight

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Pipeline: pipeline/index.md
  - QC modules:
    - qc_modules/index.md
    - Ancestry: qc_modules/ancestry.md
    - Contamination: qc_modules/contamination.md
    - Flag Hardy-Weinberg: qc_modules/flag_hw.md
    - Flag MAF: qc_modules/flag_maf.md
    - Heterozygous haploid: qc_modules/hetero_hap.md
  - API reference:
    - reference/index.md
    - QC modules:
      - Ancestry: reference/qc_modules/ancestry.md
      - Contamination: reference/qc_modules/contamination.md
      - Flag Hardy-Weinberg: reference/qc_modules/flag_hw.md
      - Flag MAF: reference/qc_modules/flag_maf.md
      - Heterozygous haploid: reference/qc_modules/hetero_hap.md

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js

extra_css:
  - style.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
