[tox]
envlist = py311,py312,py313,py314

; [gh-actions]
; python =
;     3.11: py311
;     3.12: py312
;     3.13: py313
;     3.14: py314

[testenv]
deps =
    pytest
    pytest-cov
    pytest-mock
    pytest-subprocess
commands =
    - python -V
    - pip freeze
    pytest -s --cov=pygenclean pygenclean

[coverage:run]
branch = True
